spring:
  profiles:
    active: dev
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:25432/avenger
    username: nucleo
    password: nucleo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true